services:
  web:
    build:
      context: /home/fran/devops/Docker/Caronte
      dockerfile: ./dockerfiles/pokeapinest/pokeapinest
    container_name: ctfrannestpokeapi
    image: franm88/pokeapinest
    ports:
      - 3010:3001
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs

