services:
  web:
    build:
      context: /home/fran/devops/Docker/Caronte
      dockerfile: ./dockerfiles/nodejsnext/nodenext
    container_name: ctfrannext
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    image: franm88/nexjs
    volumes:
      - ./logs:/root/logs

