services:
  web:
    build:
      context: /home/fran/devops/Docker/Caronte
      dockerfile: ./dockerfiles/nextpoke/pokenext
    container_name: ctfrannextpoke
    image: franm88/nextpoke
    ports:
      - 3010:3000
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs

